export const images = {
    backIcon: require('../assets/img_new/icon_back.png'),
    editIcon: require('../assets/img_new/icon_edit.png'),
    stepNew1: require('../assets/step/step_new_1.png'),
    stepNew2: require('../assets/step/step_new_2.png'),
    stepNew02: require('../assets/step/step_new_02.png'),
    stepNew3: require('../assets/step/step_new_3.png'),
    stepNew03: require('../assets/step/step_new_03.png'),
    stepNew4: require('../assets/step/step_new_4.png'),
    stepNew04: require('../assets/step/step_new_04.png'),
    stepNew5: require('../assets/step/step_new_5.png'),
    stepNew05: require('../assets/step/step_new_05.png'),
    hand01: require('../assets/icons/hand-01.png'),
    hand02: require('../assets/icons/hand-02.png'),
    hand03: require('../assets/icons/hand-03.png'),
    backIconColor: require('../assets/img_new/icon_back_color.png'),
    bgStep: require('../assets/img_new/bg-step.png'),
    logo2x: require('../assets/images/logo2x.png'),
    bgSuccess: require('../assets/img_new/bg_success.png'),
    logo: require('../assets/images/logo.png'),
    qrCode: require('../assets/img_new/qrcode.png'),
    bg: require('../assets/img_new/bg.png'),
    settingIcon: require('../assets/img_new/icon_setting.png'),
    refreshIcon: require('../assets/img_new/icon_refresh.png'),
    loginImg: require('../assets/img_new/img-login.png'),
    nailsBGV2: require('../assets/images/nailsbgv2.png'),
};