export const assetsImages = {
  backImage: require('../../Assets/images/backImage.png'),
  skip1: require('../../Assets/images/skip1.png'),
  skip2: require('../../Assets/images/skip2.png'),
  google: require('../../Assets/images/google.png'),
  babyNmom: require('../../Assets/images/baby&mom.png'),
  healthNbeauty: require('../../Assets/images/Health&beauty.png'),
  phone: require('../../Assets/images/Phone.png'),
  sports: require('../../Assets/images/Sports.png'),
  banner: require('../../Assets/images/banner.jpg'),
  banner1: require('../../Assets/images/banner1.png'),
  latest1: require('../../Assets/images/latest1.png'),
  latest2: require('../../Assets/images/latest2.png'),
  latest3: require('../../Assets/images/latest3.png'),
  off1: require('../../Assets/images/off1.png'),
  off2: require('../../Assets/images/off2.png'),
  off3: require('../../Assets/images/off3.png'),
  off4: require('../../Assets/images/off4.png'),
  user: require('../../Assets/images/user.png'),
  product: require('../../Assets/images/product.png'),
  image1: require('../../Assets/images/image1.png'),
  image2: require('../../Assets/images/image2.png'),
  image3: require('../../Assets/images/image3.png'),
  noImage: 'https://market2.store/wp-content/uploads/2023/07/23.jpg',
  noProfileImage: require('../../Assets/images/icon/profileNoImg.png'),
  noProfileImage2:
    'https://secure.gravatar.com/avatar/63376c697b5635a1b5fcdae4c3df3122?s=96&d=mm&r=g',
  camera: require('../../Assets/images/icon/CameraIcon.png'),
  ordersuccess: require('../../Assets/images/payemnt_suc.png'),
  //Drawer Icons

  cart2: require('../../Assets/images/icon/Cart2.png'),
  DocumentUpload: require('../../Assets/images/icon/DocumentUpload.png'),
  PaymentDetails: require('../../Assets/images/icon/PaymentDetails.png'),
  HelpSupport: require('../../Assets/images/icon/HelpSupport.png'),
  ReviewRating: require('../../Assets/images/icon/ReviewRating.png'),
  logout2: require('../../Assets/images/icon/logout.png'),
  Projection: require('../../Assets/images/icon/Projection.png'),
  TandC: require('../../Assets/images/icon/TandC.png'),

  Add: require('../../Assets/images/icon/Add.png'),
  Sub: require('../../Assets/images/icon/Sub.png'),
  arrowRight: require('../../Assets/images/icon/arrowRight.png'),
  activePen: require('../../Assets/images/icon/activePen.png'),
  inactivePen: require('../../Assets/images/icon/inactivePen.png'),
  location: require('../../Assets/images/icon/location.png'),
  wishlist: require('../../Assets/images/Wishlist.png'),
};

export const assetsIcon = {
  menu: require('../../Assets/images/icon/menu.png'),
  search: require('../../Assets/images/icon/search.png'),
  cart: require('../../Assets/images/icon/cart.png'),
  bell: require('../../Assets/images/icon/bell.png'),
  home_tab: require('../../Assets/images/icon/home.png'),
  shopping_bag: require('../../Assets/images/icon/shopping_bag.png'),
  search_tab: require('../../Assets/images/icon/search_tab.png'),
  profile_tab: require('../../Assets/images/icon/profile_tab.png'),
};
