export default Object.freeze({
  Slide: 'Slide',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  Home: 'Home',
  Bottomtab: 'Bottomtab',
  Drawertab: 'DrawerTab',
  Shopping: 'Shopping',
  SearchItem: 'SearchItem',
  Account: 'Account',
  ProductDetails: 'ProductDetails',
  ChangePassword: 'ChangePassword',
  ForgetPassword: 'ForgetPassword',
  SizeDetails: 'SizeDetails',
  Cart: 'Cart',
  RatingReview: 'RatingReview',
  SizeChart: 'SizeChart',
  Notification: 'Notification',
  ShippingAddress: 'ShippingAddress',
  Payment: 'Payment',
  PaymentSuccess: 'PaymentSuccess',
  OrderDetails: 'OrderDetails',
  HelpSupport: 'HelpSupport',
  TermsCondition: 'TermsCondition',
  Schedule: 'Schedule',
  Wishlist: 'Wishlist',
  EditProduct: 'EditProduct',
});
